version: '3'

services: 
    web:
        build: .
        command: 
            sh -c "python manage.py test accounts &&
            python manage.py test api &&
            python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
    
    redis:
        image: redis
        ports:
            - "6379:6379"