# Generated by Django 3.2.5 on 2021-07-19 07:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_location),
        ),
    ]
